In [1]:
import numpy as np
import pandas as pd


In [55]:
## Creating a matrix or array
np.random.seed(123)          # This is command for computing similare random sample always


M =np.matrix(np.random.randn(3,3))   
A = np.matrix(np.random.randint(1,10,size= (3,1)))


In [73]:
## ------------------------------ Besic propreties of matrix -------------------------------------------------##

# Common properties 
prop_dict = {'Shape':'This is a # rows and # columns in matrix','Size':'This is total # of elements in matrix','Dimention':'This for array ,matrix is alway a 2D array'}


## Commands for detrmine properties 
command_dict_M = {'Shape':M.shape ,'Size':M.size,'Dimention':M.ndim}

command_dict_A = {'Shape':A.shape,'Size':A.size,'Dimention': A.ndim}

print(command_dict_M)
print(command_dict_A)
print(command_dict_M == command_dict_A) ## Comparisen of two dictionaries 


{'Shape': (3, 3), 'Size': 9, 'Dimention': 2}
{'Shape': (3, 1), 'Size': 3, 'Dimention': 2}
False


In [65]:
## ------------------Matrix multipication addition ,substraction  and matrix inverse------------------- ##

##--------------------------------------------------------------------------------------------------------------------------------
# 1. Mat1.dot(Mat2) or 2) np.matmul(Mat1,Mat2)


##--------------------------------------------------------------------------------------------------------------------------------

Comp_dict = {'Dot':M.dot(A),'Matmul':np.matmul(M,A),'simple_mult':(M*A)}

Comp_dict['Dot'] == Comp_dict['Matmul'] 
Comp_dict['Matmul'] ==  Comp_dict['simple_mult']


# Simple addition of matix ( For addition and substraction of matrix they shoud of same shape)

add_dict = {'add_command' : np.add(M,M) ,'simple_add' : (M+M)}    

add_dict['add_command'] == add_dict['simple_add']


# Subtraction of matrix

sub_dict ={'subtract_command': np.subtract(M,M),'simple_sub':(M-M)}

sub_dict['subtract_command'] == sub_dict['simple_sub']


##--------------------------------------------------------#@@@# -----------------------------------------------------------##
##                                      Elementwise matrix multiplication                                                  ##
##--------------------------------------------------------#@@@#------------------------------------------------------------##

# It not nessary that two matrix should be are of same length

np.multiply(M,A)
np.multiply(A,np.eye(3))


matrix([[4., 0., 0.],
        [0., 5., 0.],
        [0., 0., 1.]])

In [98]:
####  Transpose ,Inverse ,Trace ,Determinate ,Rank

## Transpose of matrix 
trans_dict = {'Method_1':A.T,'Method_2':np.transpose(A)}

## Trace of matrix 
trace_dict = {'Method_1':M.trace(),'Method_2':np.trace(M)}

## Determinate of matrix 

detar_dict = {'Detminate': np.linalg.det(np.eye(3))}    ## Determinate of identiy matrix is always one 
detar_dict

## Inverse of a matrix 
inv_dict = {'Inverse': np.linalg.inv(M)}
inv_dict

## Rank of matrix 

rank_dict = {'Rank': np.linalg.matrix_rank(np.eye(3))}
rank_dict

## How to compute G inverse of a Matrix 






{'Rank': 3}

In [122]:
## -----------------------------------# System of linear Eqution # -------------------------------------------------- ##

# Genrel Formula of this Ax = b 

mat = np.matrix ([[1,2,-1],[2,1,4],[3,3,4]])
b   = np.matrix([1,2,1]).T

np.linalg.solve(mat,b)



matrix([[ 7.],
        [-4.],
        [-2.]])

In [118]:
## -----------------------------------------Decomposation of matrix-------------------------------------------------- ##

## Eigen value decomposation 
## This is compostion for the square matrix. A(mxm) = U(mxm)E(mxm)U'(mxm)

temp = np.matrix([[0,1],[-2,-3]])
values,vectors = np.linalg.eig(temp)
# print(values,vectors)

## Singular value decomposition 
## Sinagular value decompostion is s used for when the matrix is not square .  A(mxn) = U(mxm)E(mxn)V'(nxn)

U,S,Vtranspose = np.linalg.svd(temp)

print(U)
print('\n')
print(S)
print('\n')
print(Vtranspose)

[[-0.22975292  0.97324899]
 [ 0.97324899  0.22975292]]


[3.70245917 0.54018151]


[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]


In [15]:
## Error 
np.matrix(np.random.randint(10,100,size= (3,3,3)))  ## This is not possiable because matrix is special case of array and it has only two dimention  


ValueError: shape too large to be a matrix.

In [1]:
pwd


'C:\\Users\\para9004'